### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vMax-dev1** [x404xx/TempMailGenerator-1SECMAIL#1]
I have some questions, there is no integrated mailbox? because with the generator, you can store the emails, but where to find the mailbox?

**Comment by x404xx** [comment]
> I have some questions, there is no integrated mailbox? because with the generator, you can store the emails, but where to find the mailbox?

Let's say you have already generated an email and saved it. After that, try sending any message to the generated email with your other email. Then, you can try this:

```python
from api import EmailGenerator

if __name__ == "__main__":
    username = your generated username
    domain = your generated domain

    gen = EmailGenerator()
    print(gen.get_message(username, domain))
```

I hope this helps.
